✨ send_to 支持自动选择合适的 bot 进行发送
felinae98/nonebot-plugin-send-anything-anywhere pull request #39
Opened 2023-03-26 02:02 UTC by he0119

维护一个 PlatformTarget 到 bots 的表。

2023-04-03 18:25 UTC, felinae98 requested changes
1. 因为现在引入了 `auto_select_bot`，所以测试形式应该可以改回去了。
2. 最好在每一种平台发送的时候产生“找不到目标”的时候统一 raise 一个错误，然后在 send 中捕捉这个错误后，refresh 然后重新 send（这个可以未来再做）

2023-04-03 18:25 UTC, felinae98 commented on nonebot_plugin_saa/utils/get_bot.py
> +def register_get_targets(adapter: SupportedAdapters):
```suggestion
def register_list_targets(adapter: SupportedAdapters):
```

2023-04-03 18:25 UTC, felinae98 commented on nonebot_plugin_saa/utils/get_bot.py
> +def get_bot(target: PlatformTarget) -> Optional[Bot]:
这里应该检查一下是否 init，如果没有 init 的话 raise 一个错误。这是一个开发/测试环节就会遇到的问题，应该尽早抛出让开发者解决

2023-04-03 18:25 UTC, felinae98 commented on nonebot_plugin_saa/utils/get_bot.py
> +get_targets_map: dict[str, GetTargetFunc] = {}
```suggestion
list_targets_map: dict[str, GetTargetFunc] = {}
```

2023-04-03 18:25 UTC, felinae98 commented on nonebot_plugin_saa/utils/types.py
> +                bot = random_bot
这两行不应该没有覆盖到吧

2023-04-04 00:42 UTC, he0119 commented on nonebot_plugin_saa/utils/__init__.py
> +    # get_bot
hhhhhh

2023-04-04 05:21 UTC, felinae98 commented on nonebot_plugin_saa/utils/auto_select_bot.py
> +        raise RuntimeError("自动选择 Bot 的功能为启用，请先调用 enable_auto_select_bot 启用此功能")
```suggestion
        raise RuntimeError("自动选择 Bot 的功能未启用，请先调用 enable_auto_select_bot 启用此功能")
```

2023-04-04 05:21 UTC, felinae98 commented on nonebot_plugin_saa/utils/types.py
> +                raise RuntimeError("无法确定要发送的 bot")
“还未适配这种平台”和“并没有找到能发到这个target的bot”返回的结果都是这个 error，最好想办法区分一下这两种问题

2023-04-04 05:22 UTC, he0119 commented on nonebot_plugin_saa/utils/types.py
> +                raise RuntimeError("无法确定要发送的 bot")
加个新的异常？

2023-04-04 05:27 UTC, felinae98 commented on nonebot_plugin_saa/utils/types.py
> +                raise RuntimeError("无法确定要发送的 bot")
就起码 Runtime 里的 message 有点区别）

2023-04-04 05:30 UTC, he0119 commented on nonebot_plugin_saa/utils/types.py
> +                raise RuntimeError("无法确定要发送的 bot")
我记得没适配是notimplementederror吧

2023-04-05 05:46 UTC, merged

2023-04-05 07:42 UTC, he0119 commented
@ssttkkl 大佬有兴趣来适配一下开黑啦吗？

2023-04-06 02:43 UTC, ssttkkl commented
> @ssttkkl 大佬有兴趣来适配一下开黑啦吗？

OK，刚把PR提了 #44